-- ── daily_facts: vervang seed-data met verbeterde feiten ──────────────────────
-- Idempotent: TRUNCATE + herinsert vervangt altijd de hele set
-- Kolom: fact_text (NIET content — dat bestaat niet in deze tabel)
-- Categories: lowercase ('recruitment' | 'natuur' | 'algemeen') conform schema

TRUNCATE public.daily_facts RESTART IDENTITY;

INSERT INTO public.daily_facts (content, category) VALUES

-- ── RECRUITMENT (25) ─────────────────────────────────────────────────────────
('Dinsdag is statistisch gezien de populairste dag om te solliciteren.', 'recruitment'),
('Kandidaten beslissen vaak binnen 14 seconden of ze een vacaturetekst verder lezen.', 'recruitment'),
('Bedrijven met een sterk employer brand hebben 50% lagere cost-per-hire.', 'recruitment'),
('89% van de mislukte aannames is te wijten aan een gebrek aan soft skills, niet hard skills.', 'recruitment'),
('Een vacature met een salarisindicatie krijgt 30% meer sollicitaties.', 'recruitment'),
('Gemiddeld duurt het 42 dagen om een openstaande vacature te vervullen.', 'recruitment'),
('Diversiteit in teams leidt tot 19% hogere innovatie-omzet.', 'recruitment'),
('Meer dan 70% van de werkzoekenden zoekt vacatures via hun mobiele telefoon.', 'recruitment'),
('Recruiters besteden gemiddeld slechts 7 seconden aan de eerste scan van een CV.', 'recruitment'),
('Werknemers via een referral-programma blijven gemiddeld langer bij een bedrijf.', 'recruitment'),
('Gepersonaliseerde koude acquisitie e-mails hebben een 40% hogere open rate.', 'recruitment'),
('Slechte onboarding zorgt ervoor dat 20% van nieuw talent binnen 45 dagen vertrekt.', 'recruitment'),
('75% van de professionals is latent werkzoekend.', 'recruitment'),
('Kandidaten waarderen transparantie over de sollicitatieprocedure het hoogst.', 'recruitment'),
('Videocalls voor een eerste ronde besparen bedrijven gemiddeld 4 uur per aanname.', 'recruitment'),
('De vraag naar data science rollen is de afgelopen 5 jaar met 350% gestegen.', 'recruitment'),
('Gamification in assessments verlaagt het uitvalpercentage van kandidaten met 25%.', 'recruitment'),
('Generatie Z hecht meer waarde aan werksfeer en missie dan aan het startsalaris.', 'recruitment'),
('Het vermelden van flexibele werktijden trekt 20% meer vrouwelijk talent aan.', 'recruitment'),
('Een goede kandidaat-ervaring maakt de kans 38% groter dat ze een aanbod accepteren.', 'recruitment'),
('LinkedIn is verantwoordelijk voor meer dan 80% van de B2B recruitment leads.', 'recruitment'),
('AI in recruitment kan de screeningstijd tot wel 75% verminderen.', 'recruitment'),
('Bedrijven verliezen wekelijks 1 tot 2 goede kandidaten door een te traag proces.', 'recruitment'),
('Actief luisteren is de meest ondergewaardeerde skill van een toprecruiter.', 'recruitment'),
('Recruiters die emojis in hun e-mail subject lines gebruiken, zien hogere open rates.', 'recruitment'),

-- ── NATUUR & DIEREN (25) ──────────────────────────────────────────────────────
('Het hart van een garnaal zit in zijn hoofd.', 'natuur'),
('De Roodborst is onofficieel de nationale vogel van Nederland.', 'natuur'),
('Een octopus heeft 3 harten en blauw bloed.', 'natuur'),
('Koeien hebben beste vrienden en ervaren stress als ze gescheiden worden.', 'natuur'),
('Vlinders proeven met hun voeten.', 'natuur'),
('Wombat poep is kubusvormig, zodat het niet van rotsen afrolt.', 'natuur'),
('Bijen kunnen gezichten van mensen herkennen.', 'natuur'),
('Een slak kan 3 jaar achter elkaar slapen.', 'natuur'),
('Dolfijnen geven elkaar namen door middel van specifieke fluitjes.', 'natuur'),
('Olifanten zijn de enige zoogdieren die niet kunnen springen.', 'natuur'),
('Luipaarden kunnen twee keer hun lichaamsgewicht hoog een boom in tillen.', 'natuur'),
('In Nederland broeden jaarlijks ongeveer 60 paar slechtvalken, vaak op hoge gebouwen.', 'natuur'),
('Mieren rusten ongeveer 8 minuten in elke periode van 12 uur.', 'natuur'),
('Zeepaardjes houden elkaars staart vast als ze reizen om niet af te drijven.', 'natuur'),
('Een flamingo kan alleen eten als zijn kop ondersteboven hangt.', 'natuur'),
('Vleermuizen draaien altijd linksaf als ze een grot verlaten.', 'natuur'),
('Kikkers moeten hun ogen sluiten om te kunnen slikken.', 'natuur'),
('De tong van een blauwe vinvis weegt evenveel als een volwassen olifant.', 'natuur'),
('Zeeotters hebben een ingebouwd zakje van overtollig vel om hun favoriete steen in te bewaren.', 'natuur'),
('Tijgers hebben niet alleen een gestreepte vacht, maar ook een gestreepte huid.', 'natuur'),
('De ijsvogel is een van de weinige vogels in Nederland die vis uit het water duikt.', 'natuur'),
('Eekhoorns planten per ongeluk duizenden bomen per jaar door vergeten nootjes.', 'natuur'),
('Een struisvogel oog is groter dan zijn brein.', 'natuur'),
('Gierzwaluwen kunnen maandenlang vliegen zonder de grond te raken.', 'natuur'),
('Grasmussen navigeren tijdens hun migratie op de sterren.', 'natuur'),

-- ── ALGEMEEN / FUN FACTS (25) ──────────────────────────────────────────────
('Honing is het enige voedsel dat nooit bederft. Er is eetbare honing gevonden in Egyptische tombes.', 'algemeen'),
('Op Venus duurt een dag langer dan een jaar.', 'algemeen'),
('Er zitten meer sterren in het heelal dan zandkorrels op alle stranden van de aarde.', 'algemeen'),
('Witte chocolade bevat eigenlijk geen cacaobestanddelen en is technisch gezien geen chocolade.', 'algemeen'),
('Oxford University is ouder dan het Azteekse rijk.', 'algemeen'),
('Frankrijk was het laatste land dat de guillotine gebruikte, in 1977.', 'algemeen'),
('Nintendo werd opgericht in 1889, in de tijd van Jack the Ripper.', 'algemeen'),
('De aarde draait met ruim 1600 km/u rond haar eigen as.', 'algemeen'),
('De Eiffeltoren kan in de zomer wel 15 centimeter groter worden door hitte-uitzetting.', 'algemeen'),
('Pinda''s zijn geen noten, maar peulvruchten.', 'algemeen'),
('Er is een soort kwal die biologisch onsterfelijk is (Turritopsis dohrnii).', 'algemeen'),
('Watermeloenen bestaan voor 92% uit water.', 'algemeen'),
('De langste hik-aanval ter wereld duurde 68 jaar.', 'algemeen'),
('Goud is eetbaar als bladzilver of bladgoud.', 'algemeen'),
('Ongeveer 10% van de wereldbevolking is linkshandig.', 'algemeen'),
('De eerste wekker kon alleen maar om 4 uur ''s ochtends afgaan.', 'algemeen'),
('Ketchup werd in de 19e eeuw verkocht als medicijn.', 'algemeen'),
('Je deelt je geboortedag met minimaal 19 miljoen andere mensen ter wereld.', 'algemeen'),
('Een wolk kan gemiddeld zo''n 500.000 kilo wegen.', 'algemeen'),
('Het langste Engelse woord zonder klinkers is ''rhythms''.', 'algemeen'),
('Een potlood heeft genoeg grafiet om een lijn van 56 kilometer lang te trekken.', 'algemeen'),
('Er is een wolk van alcohol in de ruimte die miljarden liters bevat.', 'algemeen'),
('De eenhoorn is het nationale dier van Schotland.', 'algemeen'),
('Appels, perziken en frambozen behoren allemaal tot de rozenfamilie.', 'algemeen'),
('Het duurt 8 minuten en 20 seconden voor zonlicht de aarde bereikt.', 'algemeen');
